#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pbzip2
Version  : 1.1.12
Release  : 2
URL      : https://launchpad.net/pbzip2/1.1/1.1.12/+download/pbzip2-1.1.12.tar.gz
Source0  : https://launchpad.net/pbzip2/1.1/1.1.12/+download/pbzip2-1.1.12.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pbzip2-bin
Requires: pbzip2-doc
BuildRequires : bzip2-dev
Patch1: build.patch

%description
PBZIP2 is a parallel implementation of the bzip2 block-sorting file
compressor that uses pthreads and achieves near-linear speedup on SMP
machines.  The output of this version is fully compatible with bzip2
v1.0.2 or newer (ie: anything compressed with pbzip2 can be 
decompressed with bzip2).

%package bin
Summary: bin components for the pbzip2 package.
Group: Binaries

%description bin
bin components for the pbzip2 package.


%package doc
Summary: doc components for the pbzip2 package.
Group: Documentation

%description doc
doc components for the pbzip2 package.


%prep
%setup -q -n pbzip2-1.1.12
%patch1 -p1

%build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export CFLAGS="$CFLAGS -fno-semantic-interposition -ffunction-sections -O3 -flto "
export CXXFLAGS="$CXXFLAGS -fno-semantic-interposition -ffunction-sections -O3 -flto "
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pbunzip2
/usr/bin/pbzcat
/usr/bin/pbzip2

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
