#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD332F1B09A0D9836 (nikolov.javor@gmail.com)
#
Name     : pbzip2
Version  : 1.1.13
Release  : 12
URL      : https://launchpad.net/pbzip2/1.1/1.1.13/+download/pbzip2-1.1.13.tar.gz
Source0  : https://launchpad.net/pbzip2/1.1/1.1.13/+download/pbzip2-1.1.13.tar.gz
Source1 : https://launchpad.net/pbzip2/1.1/1.1.13/+download/pbzip2-1.1.13.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : bzip2-1.0.6
Requires: pbzip2-bin = %{version}-%{release}
Requires: pbzip2-license = %{version}-%{release}
Requires: pbzip2-man = %{version}-%{release}
BuildRequires : bzip2-dev
Patch1: build.patch

%description
PBZIP2 is a parallel implementation of the bzip2 block-sorting file
compressor that uses pthreads and achieves near-linear speedup on SMP
machines.  The output of this version is fully compatible with bzip2
v1.0.2 or newer (ie: anything compressed with pbzip2 can be 
decompressed with bzip2).

%package bin
Summary: bin components for the pbzip2 package.
Group: Binaries
Requires: pbzip2-license = %{version}-%{release}

%description bin
bin components for the pbzip2 package.


%package license
Summary: license components for the pbzip2 package.
Group: Default

%description license
license components for the pbzip2 package.


%package man
Summary: man components for the pbzip2 package.
Group: Default

%description man
man components for the pbzip2 package.


%prep
%setup -q -n pbzip2-1.1.13
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568082142
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1568082142
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pbzip2
cp COPYING %{buildroot}/usr/share/package-licenses/pbzip2/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pbunzip2
/usr/bin/pbzcat
/usr/bin/pbzip2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pbzip2/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pbzip2.1
